version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
  stats:
    build:
      context: .
      dockerfile: Dockerfile
    command: '--get-stats --users-host db --dojos-host db --events-host db'
    volumes:
      - ./stats:/usr/src/app/stats
    depends_on:
      - db
