version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
  stats:
    image: coderdojo/stats
    command: '-so --users-host db --dojos-host db --events-host db'
    volumes:
      - ./stats:/usr/src/app/stats
    depends_on:
      - db
